### ISSUE TITLE
Merge the initial starting point into the package and add in tests

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/Expectations.jl#2]
https://github.com/jlperla/ECON407_2018/blob/master/notebooks/expectations_integration.ipynb

**Comment by arnavs** [comment]
I think this is done now, modulo the discussed changes that (a) we use Gauss-Legendre instead of adaptive Gauss-Kronod, and (b) our `IterableExpectation` type should hold nodes and weights instead of a functional `func: f -> quadgk(blahblahblah)`.  

So will close. But if I'm missing something, @jlperla can re-open.
