### ISSUE TITLE
Remove deprecations from the unit tests in preparation for v1.0

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/Expectations.jl#22]
I don't think there are any deprecations in the current `/src`, but there seems to be at least one in the tests.  Doing a `Pkg.test("Expectations")` gives output that includes
```julia
WARNING: importing deprecated binding Base.e into Expectations.
┌ Warning: `linspace(start, stop, length::Integer)` is deprecated, use `range(start, stop=stop, length=length)` instead.
│   caller = top-level scope at none:0
└ @ Core none:0
┌ Warning: `linspace(start, stop, length::Integer)` is deprecated, use `range(start, stop=stop, length=length)` instead.
│   caller = top-level scope at none:0
└ @ Core none:0
Test Summary:          | Pass  Total
Iterable distributions |   38     38
   Testing Expectations tests passed
```

I am not sure where the `e` is used, but the `linspace` is easy enough to replace... using `Compat` as required.

**Comment by arnavs** [comment]
Done. `linspace` was coming from the algorithm for `QuantileLinSpace` (which I renamed `QuantileRange` to be more Julian). Can't find any uses of `e`, so I suspect that's coming to us by means of a dependency (or going from normal to lognormal, or something). 

Also, @jlperla, this confirms that you were working off an old copy, because the new one (with the convenience calls) has 43 tests (+5 for the convenience calls).
